name 'dhoppe-dpkg'
version '0.1.0'

author 'Dennis Hoppe'
license 'GPLv2'
project_page 'http://github.com/dhoppe/puppet-dpkg'
source 'git://github.com/dhoppe/puppet-dpkg'
summary 'DPKG Module'
description 'DPKG Module for Debian, Ubuntu'
dependency 'puppetlabs/stdlib', '>=0.0.1'
